import { BookOpen, Library, Menu, Settings, X } from 'lucide-react'
import { useState } from 'react'
import { NavLink, Outlet } from 'react-router-dom'
import { Container } from '@/components/ui/Container'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import { cn } from '@/lib/cn'

const links = [{ to: '/', label: 'Home', icon: BookOpen }, { to: '/library', label: 'Library', icon: Library }, { to: '/settings', label: 'Settings', icon: Settings }]
export function MainLayout() { const [open, setOpen] = useState(false); return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b border-border/80 bg-background/85 backdrop-blur"><Container className="flex h-16 items-center justify-between"><NavLink to="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><BookOpen className="size-4" /></span>EchoRead</NavLink><div className="flex items-center gap-2"><nav className="hidden items-center gap-1 md:flex">{links.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => cn('flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground', isActive && 'bg-secondary text-foreground')}><Icon className="size-4" />{label}</NavLink>)}</nav><ThemeToggle /><button className="rounded-lg p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div></Container>{open && <Container className="border-t border-border py-3 md:hidden"><nav className="grid gap-1">{links.map(({ to, label }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-sm hover:bg-muted">{label}</NavLink>)}</nav></Container>}</header><main><Container className="py-10 sm:py-14"><Outlet /></Container></main></div> }
